###
POST http://localhost:8090/api/v1/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMjA0MSwiZXhwIjoxNjU1NDE1NjQxLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.aPuB0LUxvo-p4Mq1cmyvAYT8PFhJ2mSAP--37g_RZOw

{
  "name" : "Holmat",
  "surname" : "Toshmatov",
  "email" : "wtykjhvcxz@gmail.com",
  "password" : "123432",
  "phone": "+9989011502030",
  "country": "Ukraina"
}


###
GET http://localhost:8090/api/v1/profile/adm/pagination
Content-Type: application/json


###
PUT http://localhost:8090/api/v1/profile/adm/update/8a8a83d2816df8bf01816dfa889f0000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMjA0MSwiZXhwIjoxNjU1NDE1NjQxLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.aPuB0LUxvo-p4Mq1cmyvAYT8PFhJ2mSAP--37g_RZOw

{
  "name" : "wertyuiop",
  "surname" : "rtyuiop[",
  "email" : "ertyuiop[@gmail.com",
  "password" : "wsedrftyuiop",
  "phone": "+9989011507485",
  "country": "Ukraina"
}

###
DELETE http://localhost:8090/api/v1/profile/adm/delete/8a8a83d2816e3eef01816e3f7fea0000
Content-Type: application/json

