###
POST http://localhost:8090/api/v1/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQ1OTU1MywiZXhwIjoxNjU1NDYzMTUzLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.6Z38yGLZ8Un7BcZ5sMyJV7rkDl1OYP3PwrgLAj7Z44A

{
  "product_id": "8a8a83d2817123620181712758320000"
}

###
GET http://localhost:8090/api/v1/order/getList
Content-Type: application/json


###orderlarni listini olish uchun profile id bilan narsa create qilish esingdan chiqmasin  agar create qilmagan profile idni bersang ishlmedi

GET http://localhost:8090/api/v1/order/getProfileOrderList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MDI4YWIzNTgxNWQyMjIxMDE4MTVkMjNlM2FkMDAwMCIsImlhdCI6MTY1NTI3NjQyNiwiZXhwIjoxNjU1MjgwMDI2LCJpc3MiOiJrdW4udXoiLCJyb2xlIjoiVVNFUiJ9.CaYHg9oY3AFrdlol5_AqUvvtREtVYTa_gMM2hclKrZ0
