POST http://localhost:8090/api/v1/auth/login
Content-Type:  application/json


{
  "email": "madmusayev@gmail.com",
  "password": "wsedrftyuiop"
}



###
POST http://localhost:8090/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "Abdulbori",
  "surname": "Madmusayev",
  "email": "madmusayev@gmail.com",
  "password": "12345",
  "phone": "+998999008081",
  "country": "UZBEK"
}