###
POST http://localhost:8090/api/v1/information/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQ1OTU1MywiZXhwIjoxNjU1NDYzMTUzLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.6Z38yGLZ8Un7BcZ5sMyJV7rkDl1OYP3PwrgLAj7Z44A

{
  "age_limit": "12",
  "language": "uzbek",
  "duration": "01.07.2022",
  "back_date_ticket": "20.07.2022"
}


###
POST http://localhost:8090/api/v1/information/adm/update/8a8a83d2817112330181711722820003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQ1OTU1MywiZXhwIjoxNjU1NDYzMTUzLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.6Z38yGLZ8Un7BcZ5sMyJV7rkDl1OYP3PwrgLAj7Z44A

{
  "age_limit": "14",
  "language": "Rus",
  "duration": "01.08.2022",
  "back_date_ticket": "18.07.2022",
  "product_id": "8a8a8395815565510181556ab1770000"
}

<> 2022-06-12T201444.200.json


###
GET http://localhost:8090/api/v1/information/adm/getById/8a8a83d2817112330181711722820003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQ1OTU1MywiZXhwIjoxNjU1NDYzMTUzLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.6Z38yGLZ8Un7BcZ5sMyJV7rkDl1OYP3PwrgLAj7Z44A


<> 2022-06-12T201948.200.json


###
DELETE http://localhost:8090/api/v1/information/adm/delete/8a8a83d2817112330181711722820003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQ1OTU1MywiZXhwIjoxNjU1NDYzMTUzLCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.6Z38yGLZ8Un7BcZ5sMyJV7rkDl1OYP3PwrgLAj7Z44A


<> 2022-06-12T202024.200.txt





