POST http://localhost:8090/api/v1/category/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMzExNCwiZXhwIjoxNjU1NDE2NzE0LCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.e73Lz4TKor4LX_32z7ewPz13nxG0HTMGuU3AVZFjx4Y

{
  "key" : "dfghjhgfds",
  "name_uz" : "dfghjkl;",
  "name_ru" : "dfghjk",
  "name_en" : "xcvbnm,."
}

###
GET http://localhost:8090/api/v1/category/adm/8a8a83d2816e463c01816e4fe4010000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMzExNCwiZXhwIjoxNjU1NDE2NzE0LCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.e73Lz4TKor4LX_32z7ewPz13nxG0HTMGuU3AVZFjx4Y


###
PUT http://localhost:8090/api/v1/category/adm/8a8a83d2816e463c01816e4fe4010000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMzExNCwiZXhwIjoxNjU1NDE2NzE0LCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.e73Lz4TKor4LX_32z7ewPz13nxG0HTMGuU3AVZFjx4Y

{
  "key" : "vsdacqevfadsqevfas",
  "name_uz" : "Iqtisodiyot",
  "name_ru" : "Экономика",
  "name_en" : "Economics"
}

###
DELETE http://localhost:8090/api/v1/category/adm/8a8a83d2816e463c01816e4fe4010000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYWRtdXNheWV2QGdtYWlsLmNvbSIsImlhdCI6MTY1NTQxMzExNCwiZXhwIjoxNjU1NDE2NzE0LCJpc3MiOiJpVGljZXQudXoiLCJyb2xlIjoiQURNSU4ifQ.e73Lz4TKor4LX_32z7ewPz13nxG0HTMGuU3AVZFjx4Y

<> 2022-06-17T020609.200.txt