###
POST http://localhost:8090/api/v1/product/adm/create
Content-Type: application/json

{
  "name": "Humo arena",
  "attach_id": "d698322e-36f5-478e-8ef9-db22e28658e4",
  "category_id": "4028ab35815d27d101815d31191d0003",
  "address_id":"4028ab35815d27d101815d3220170004",
  "description": "Juda zo'r bo'ladi",
  "durationDate": "2022.06.30",
  "to_amount": "20000",
  "from_amount": "20000000"
}

###
PUT http://localhost:8090/api/v1/product/adm/update/8a8a83d2815eb67101815eb77d150000
Content-Type: application/json

{
  "name": "",
  "attach_id": "",
  "category_id": "",
  "address_id":"",
  "description": "",
  "durationDate": "2022.06.30",
  "to_amount": "20000",
  "from_amount": "20000000"
}

###
GET http://localhost:8090/api/v1/product/adm/getById/8a8a83d2815eb67101815eb77d150000
Content-Type: application/json

###
DELETE http://localhost:8090/api/v1/product/adm/delete/8a8a83d2815eb67101815eb77d150000
Content-Type: application/json

###
GET http://localhost:8090/api/v1/product/adm/pagination
Content-Type: application/json


